name: My Workflow

on: 
  workflow_dispatch:
    inputs:
      message:
        description: "Message to echo"
        required: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - run: echo "workflow1 entered"